[package]
name = "nuc_profile"
version = "0.1.0"
authors = ["Ümit Akköse <umieat@gmail.com>"]
edition = "2018"


[dependencies]
anyhow = "1.0.34"
clap = "3.0.0-beta.2"
itertools = "0.10.0"
seq_io = "0.3.1"
